config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user/registrations' }
  resources :users, only: [:show]
  resources :friendships
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'search_stocks', to: 'stocks#search'
  resources :user_stocks, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  def self.new_from_search(ticker_symbole)
    StockQuote::Stock.new(api_key: 'pk_f779964c19e24d7aa8ffc428c87663c3')
    loocked_up_stock = StockQuote::Stock.quote(ticker_symbole)
    new(name: loocked_up_stock.company_name, ticker: loocked_up_stock.symbol, last_price: loocked_up_stock.latest_price)
  rescue Exception => e
    nil
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  has_many :friendships
  has_many :friends, through: :friendships
  def stock_already_adedd?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end

  def under_stock_limit?
    (user_stocks.count < 10)
  end

  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_adedd?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}".strip if first_name || last_name
    'anonymous'
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    User.where("#{field_name} like ?", "%#{param}%")
  end

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param))
    return nil unless to_send_back
    to_send_back
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end

  def except_current_user(users)
    users.reject { |user| user.id == id }
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  
    def destroy
      @friendship = current_user.friendships.where(friend_id: params[:id]).first
      @friendship.destroy
      flash[:success] = "Friend was successfully removed"
      redirect_to my_friends_path
    end
    
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].blank?
      flash.now[:danger] = 'You have entered an empty search string'
    else
      @stock = Stock.new_from_search(params[:stock])
      flash.now[:danger] = 'You have entered an incorrect symbol' unless @stock
    end
    respond_to do |format|
      format.js { render partial: 'users/results' }
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by_ticker(params[:stock_ticker])
    if stock.blank?
      stock = Stock.new_from_search(params[:stock_ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:success] = "Stock #{@user_stock.stock.name} added succussfully"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(stock_id: stock.id, user_id: current_user.id).first
    user_stock.destroy
    flash[:notice] = 'Success stock was deleted'
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @user_stocks = current_user.stocks
  end

  def my_friends
    @friendships = current_user.friends
  end

  def search
    if params[:search_param].blank?
      flash.now[:danger] = 'You have entered an empty search string'
    else
      @users = User.search(params[:search_param])
      flash.now[:danger] = 'No users match this search criteria' if @users.blank?
    end
    respond_to do |format|
      format.js { render partial: 'friends/result' }
    end
  end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)
    if current_user.save
      flash[:notice] = 'Friend was successfully added'
    else
      flash[:danger] = 'There was something wrong with the friend request'
    end
    redirect_to my_friends_path
  end

  def show
    @user = User.find(params[:id])
    @user_stocks = @user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_lookup.html.erb
<h3>Search for Friends</h3>
<div id="friend-lookup">
  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-8">
        <%= text_field_tag :search_param, params[:search_param],
        placeholder: "Enter name or email", autofocus: true,
        class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-4">
        <%= button_tag(type: :submit, class: "btn btn-block btn-success") do %>
          <i class="fa fa-search"></i> Search
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="results">
  <%= render 'friends/result' %>
</div>

app/views/friends/_result.html.erb
   <% if params[:action]=="search" %>
     <%= render 'layouts/messages' %>
   <% end %>
   <% if @users %>
   <% if @users.size > 0 %>
  <div id="friend-lookup-results" class="well results-block col-md-12">
    <table class="search-results-table col-md-12">
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><strong>Name:</strong> <%= user.full_name %></td>
            <td><strong>Email:</strong> <%= user.email %></td>
            <td><strong>Profile:</strong> <%= link_to "View Profile", user_path(user),
                                        class: "btn btn-xs btn-success" %>
              <% if current_user.not_friends_with?(user.id) %>
                <%= link_to "Add as my friend", 
                        add_friend_path(user: current_user, friend: user),
                          class: "btn btn-xs btn-primary", method: :post %>
              <% else %>
                <span class="badge badge-primary">
                  You are friends
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>
<% end %>

app/views/friends/_result.js.erb
$('#results').html("<%= j (render 'friends/result.html') %>")

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <% if key=="notice" %>
     <div class="alert alert-success">
  <% elsif key=="alert" %>
  <div class="alert alert-danger">
  <% else %>
     <div class="alert alert-<%= key %>">
  <% end %>
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
  
  
<% end %>

app/views/layouts/_navigations.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <div class="container">
      <a class="navbar-brand" href="#">Finance Trakt</a>
      <% if current_user %>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <%= link_to "My Portfolio", my_portfolio_path ,class:"nav-link" %>
          </li>
          <li class="nav-item">
            <li><%= link_to "My Profile", edit_registration_path(current_user),class:"nav-link" %></li>
          </li>
          <li class="nav-item">
              <li><%= link_to "Friends", my_friends_path,class:"nav-link" %></li>
          </li>
        </ul>

        <ul class="nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right nav-link text-white">
          <i class="fa fa-user"></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
          </li>
          <li class="col-md-4 logout">
            <%= link_to("logout", destroy_user_session_path,
                                class: "btn btn-xs btn-danger", method: :delete) %>
          </li>
        </ul>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTrakt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigations' %>
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-8">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
      
    </div>
   

  </div>
  </body>
</html>

app/views/stocks/_lists.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user.id == current_user.id %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |user_stock| %>
      <tr>
        <td><%= user_stock.name %></td>
        <td><%= user_stock.ticker %></td>
        <td><%= user_stock.last_price %></td>
        <% if @user.id == current_user.id %>
          <td><%= link_to "Delete this stock", user_stock_path(user_stock), 
                      method: :delete,
                      data: {confirm: "Are you sure?"}, 
                      class: "btn btn-xs btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_results.html.erb
   <% if params[:action]=="search" %>
     <%= render 'layouts/messages' %>
   <% end %>
    
    <% if @stock %>
        <div class="well results-block">
            <strong>name :</strong> <%= @stock.name %>
            <strong>Symbol :</strong> <%= @stock.ticker %>
            <strong>Price :</strong> <%= @stock.last_price %>
            <% if current_user.can_add_stock?(@stock.ticker) %>
                  <%= link_to 'add to my stocks', user_stocks_path(user: current_user,stock_ticker:@stock.ticker),
                class:"btn btn-xs btn-success",method: :post %>
              
            <% else %>
                  <span class="label label-default">
                    Stock cannot be added because you have already added
                    <% if !current_user.under_stock_limit? %>
                    10 stocks
                    <% end %>
                    <% if current_user.stock_already_adedd?(@stock.ticker) %>
                    this stock
                    <% end %>
                </span>
            <% end %>
          
        </div>
    <% end %>

app/views/users/_results.js.erb
$('#results').html("<%= j (render 'users/results.html') %>")

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>
<% if @friendships.size > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="3" class="page-header">
          <h2>My Friends</h2>
        </th>
      </tr>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friendships.each do |friend| %>
        <tr>
          <td><%= friend.full_name %></td>
          <td><%= friend.email %></td>
          <td>
            <%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs" %>
            <%= link_to "Remove Friend", friendship_path(friend), method: :delete,
              data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <table>  
<% else %>
  <div class="row col-lg-12">
    <p class="lead">
      You don't have any friends yet, please add some!
    </p>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>

<h2>Search for stock</h2>

<div class="stock-lookup">

    <%= form_tag search_stocks_path,remote:true,method: :get ,id:"stock-lookup-form" do %>
        <div class="form-group row no-padding text-center col-md-12">
            <div class="col-md-8">
                <%= text_field_tag :stock,params[:stock],placeholder:"stock ticker symbol",autofocus: true ,class:"form-control search-box input-lg" %>
            </div>
         
        </div>
           <div class="col-md-4">
                <%= button_tag(type: :submit,class:"btn btn-primary") do %>
                    Look up stock
                <% end %>

            </div>
    <% end %>
<div id="results">
    <%= render "users/results" %>
</div>

<%= render 'stocks/lists' %>
   
</div>

app/views/users/show.html.erb
<h2>User Details</h2> 

<dl class="dl-horizontal"> 
  <dt><strong>Full Name</strong></dt> 
  <dd><%= @user.full_name %></dd> 
  <dt><strong>Email</strong></dt> 
  <dd><%= @user.email %></dd> 
</dl> 

<% if @user.stocks.size > 0 %> 
  <%= render 'stocks/lists' %> 
<% else %> 
  <p class="lead">This user is not tracking any stocks</p> 
<% end %> 

<%= link_to "Back", my_friends_path, class: "btn btn-primary" %>

app/views/welcome/index.html.erb
<h2>Welocome To Finance Trakt</h2>